# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def sum_even_fibonacci

  fibonacci = [0, 1]
  idx1 = 0
  idx2 = 1
  while true
    next_num = fibonacci[idx1] + fibonacci[idx2]
    if next_num > 3999999 
    	break
    end
    fibonacci << next_num
    idx1 += 1
    idx2 += 1
  end

  fibonacci.delete_if {|x| x.odd?}
  fibonacci.inject(:+)

end


sum_even_fibonacci
